#!/usr/bin/env python3
"""
Read a scrapy file containing persistent queue information.

Files are stored in a binary format using pickle and queuelib.
"""
import pickle
import struct
import sys

from queuelib.queue import FifoDiskQueue


buffer = sys.stdin.buffer.read()
while buffer:
    header, buffer = buffer[:FifoDiskQueue.szhdr_size], buffer[FifoDiskQueue.szhdr_size:]
    size, = struct.unpack(FifoDiskQueue.szhdr_format, header)

    data, buffer = buffer[:size], buffer[size:]
    print(pickle.loads(data))
